[package]
name = "string"
version = "0.1.0"
authors = ["cyborg"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.1.0"
rand = "0.7.2"

[lib]
name = "string"
crate-type = ["cdylib"]
